### PR TITLE
Refactor/remove deprecated

### PR DESCRIPTION
**Pull request by JarbasAl**
removes code that is now better served by using plugins, we dont want to maintain these or encourage it's usage anymore

- phonemes (opm)
- tts (opm)
- lang detect (opm)
- translate (opm)
- i2c detect ( [phal](https://github.com/OpenVoiceOS/ovos_PHAL/pull/1) )
- enclosure template ( [opm](https://github.com/OpenVoiceOS/OVOS-plugin-manager/pull/6l) )
- color utils - out of scope for ovos functionality, old utils i used to control color of light bulbs
- parse utils - extracted from wikipedia_for_humans and outdated, largely replaced by quebra_frases

### CODE REVIEW

**Review by NeonDaniel — COMMENTED** [review]
I would suggest stubbing removed methods to prevent import errors, otherwise version should technically be bumped to 1.0.0 since this contains breaking changes

**Comment by JarbasAl** [comment]
was hoping to get a new major release together with ovos-core 0.0.2, so now is the time for breaking changes!

**Comment by ChanceNCounter** [comment]
Per semver you're right. However, by accident but to helpful effect, we've been in the habit of using semver a digit over until we're ready to go gold.

PyPI doesn't care for it, but the idea is that, since this is alpha or otherwise "prerelease" software, there *is* no version 1. Since there hasn't been a version 1, we can't indicate breaking changes with the major version; it stays 0 to indicate that this isn't even stable enough to give to consumers.

Hence, we've been breaking prerelease libs on the middle number, updating them on the last number, and patching them on the release number.

**Comment by ChanceNCounter** [comment]
@JarbasAl Daniel's right in that it's more than a bump. 0.1.0x1?

Other than that, this working or not should be a yes/no for a given importer. So far I've only seen this on mobile. Is everything that was removed now stubbed, and do the stubs whine about the plugins? We obviously don't want to make any plugins direct deps of utils, because circle, and because they're supposed to be optional.

**Comment by JarbasAl** [comment]
no stubs so far, plain old breaking change. 

since we are not even in 0.1.0 i dont think semver applies, until 0.1.0 i think everything is ok since the lib is obviously not stable, ie, any version bump is akin to a major version until we reach 0.1.0

i suspect i am the only user of these methods, they really are obscure and very niche

**Comment by NeonDaniel** [comment]
> no stubs so far, plain old breaking change.
> 
> since we are not even in 0.1.0 i dont think semver applies, until 0.1.0 i think everything is ok since the lib is obviously not stable, ie, any version bump is akin to a major version until we reach 0.1.0
> 
> i suspect i am the only user of these methods, they really are obscure and very niche

I have spec'd `ovos-utils~=0.0.1` in a few places, so I'm not sure it's a safe assumption that breaking changes won't affect existing code.. Is there any reason to not mark the first breaking change since 0.0.1 as `0.1.0`?

**Comment by JarbasAl** [comment]
its not the first breaking change is it? i mean, package changed name from jarbas_utils, cant be more breaking than that :P

**Comment by NeonDaniel** [comment]
> its not the first breaking change is it? i mean, package changed name from jarbas_utils, cant be more breaking than that :P

Maybe not; I think I was on alphas until around 0.0.12, so I might have missed breaking changes between non-alpha versions.. 
Anyway, I think we are at a stage in development where the dependencies of `ovos-core 0.0.2` should be able to be loosely spec'd (~=0.1, ~=0.0.4, etc)

**Comment by ChanceNCounter** [comment]
I'm inclined to agree. The era of CI cometh.

**Comment by JarbasAl** [comment]
once ovos-core 0.0.2 is ready we should have a general look around our utility packages and make a proper release for each that can be pinned in ovos-core

if anyone has suggestions for things that should land before 0.1.0 now is the time to do it!

**Pull request merged**
